### ISSUE TITLE
Seeing this engine just makes me depressed

### ISSUE THREAD

**Issue by rayanmargham** [FNF-CNE-Devs/CodenameEngine#110]
Legit I thought I had the brand new next big thing to do that'll help the FNF modding community a ton by adding 3D getting rid of haxeflixel throwing that shit out the window in favor of a custom game engine written in rust but when I saw the ram usage of this engine I realized that someones already done better things then me, someones already made something better

No matter how hard I try i'll always be beat and without hundreds of hours at my disposal I won't be able to compete with this engine :(

I shouldn't even call myself a programmer compared to people like the CNE devs

I know this isn't an issue but just wasn't to say that congrats on making a really good engine

**Comment by voiddevv** [comment]
yes you can believe in you're self and plus i may not know you but you must have a better personality then yoshi crafter tbh 👍🏻

**Comment by dodecaspheeb** [comment]
i think that's what someone said when they saw kade engine for the first time.

don't give up. keep working on your engine chum

**Comment by SIG7Pro** [comment]
This is making me sad to read.

**Comment by YoshiCrafter29** [comment]
the fact that theres another engine that you think is "better" out there shouldnt be whats stopping you from continuing yours

you arent a bad developer, the fact you made an entire game engine in rust is amazing, hell it prob runs better than codename does

i also felt unmotivated from times to times, mainly due to the fact people are still going to stick to psych even if codename comes out, but have i stopped? no.

if its a passion for you, continue. dont let anything else get through your path. you dont need to compete with codename, youre already succeeding in your own way

hope that makes u feel better
