### ISSUE TITLE
Bug Report: process creation failure: attrib +h .temp

### ISSUE THREAD

**Issue by StripeAndFlame** [FNF-CNE-Devs/CodenameEngine#291]
Every version of the build i try and start it gives me the message "process creation failure: attrib +h .temp"
Can ya'll help
I'm on windows

**Comment by 2Schoolhouse** [comment]
> Every version of the build i try and start it gives me the message "process creation failure: attrib +h .temp" Can ya'll help I'm on windows

Perhaps it's some of your hardware specs? Even your Windows version could be something part of it.

**Comment by NexIsDumb** [comment]
Okay so basically, this is something that we fixed in the Dev version that we'll release once the big update is done
What that line (which was crashing for many people) did is basically turn the .temp folder into a secret one for windows OS; Now in the new version we added the safe method, so even if its gonna fail putting it as hidden it wont crash but I assume the main threat of it not becoming hidden was basically because of antiviruses
Either way, if you want it fixed before the new update you can just modify the source, modify this [line](https://github.com/FNF-CNE-Devs/CodenameEngine/blob/814bd712fe2ea2dd21116e9903d9c2babe5341b1/source/funkin/backend/system/MainState.hx#L70) turning it into:

```haxe
#if windows
try new funkin.backend.utils.native.HiddenProcess("attrib +h .temp")
catch(e) Logs.warn('Failed to set hidden attribute on .temp folder');
#end
```

**Comment by StripeAndFlame** [comment]
Ok but what if you get a build from actions, is there a way to fix if you have a build from there?

**Comment by 2Schoolhouse** [comment]
> Ok but what if you get a build from actions, is there a way to fix if you have a build from there?

In that case, then no. Action builds are already compiled, so you cannot change the source code through them.

**Comment by NexIsDumb** [comment]
> > Ok but what if you get a build from actions, is there a way to fix if you have a build from there?
> 
> In that case, then no. Action builds are already compiled, so you cannot change the source code through them.

Yeah, unfortunately you can't unless you pick an old version of the action builds; Just wait a bit, the update is not too much far away either way

**Comment by mikeieyt** [comment]
ive had the same but it said Process Creation Failiure: wmic

**Comment by r6915ee** [comment]
> ive had the same but it said Process Creation Failiure: wmic

I personally would not prefer to necropost a year-old issue; but, to answer your question, you may need to install it as an optional feature. Windows 11 disables it by default if I remember correctly, so you have to go into any of the feature configuration menus and enable it from there, wait for the system to update, and then that error should be gone. This isn't _entirely_ a Codename issue, but it is affected by it.
