### ISSUE TITLE
how can i use a custom FlxSprite class in another state in mods?

### ISSUE THREAD

**Issue by NotMrPolo-real** [FNF-CNE-Devs/CodenameEngine#460]
for example when i wanted to add a custom extended FlxSprite class i would to do something like this in the source code:

```
package states;

Class CoolStuffState extends MusicBeatState
{
	var characterSprite:CharSprite = new CharSprite();
	add(characterSprite)
	// stuff...
}

Class CharSprite extends FlxSprite
{
	// other stuff...
}
```
but in the mods folder idk how to do that, any help?

**Comment by PetscopF** [comment]
> for example when i wanted to add a custom extended FlxSprite class i would to do something like this in the source code:
> 
> ```
> package states;
> 
> Class CoolStuffState extends MusicBeatState
> {
> 	var characterSprite:CharSprite = new CharSprite();
> 	add(characterSprite)
> 	// stuff...
> }
> 
> Class CharSprite extends FlxSprite
> {
> 	// other stuff...
> }
> ```
> 
> but in the mods folder idk how to do that, any help?

As far as I'm aware, you don't really define packages and classes when softcoding; that's not really how it entirely works. The game loads everything at particular points in time, so doing this might give you problems.

With that said, why would you need to define these, isolated from the rest of the scripts in this format? A package setup likely won't work in this context, since HScript doesn't really use packages. If you needed a new state, you would simply make the file for it but use Codename [callbacks](https://codename-engine.com/wiki/modding/scripting/script-calls) such as `create()` or `update()` and then load into it as a `ModState` with the first parameter in the constructor being the respective file (starting from the states folder).

**Comment by NotMrPolo-real** [comment]
oh that was just for an example i forgot to delete the "package states" dont mind that
i just want to know how to call/use another state(class) into another state in the mods folder

**Comment by PetscopF** [comment]
> oh that was just for an example i forgot to delete the "package states" dont mind that i just want to know how to call/use another state(class) into another state in the mods folder

For that, you would need to switch to a fresh ModState with the state script being within the `data/states` directory for your mod. For example, if your state's filename was `GorillaState.hx` and was located within the root of the states directory, you would use this function:

```haxe
FlxG.switchState(new ModState("GorillaState"));
```

**Comment by NotMrPolo-real** [comment]
i dont think your understand what i mean

i want to use a custom "FlxSprite" class in a "MusicBeatState" state
just like the example showen

**Comment by Moro-Maniac** [comment]
> but in the mods folder idk how to do that, any help?

https://codename-engine.com/wiki/modding/scripting/custom-classes

**Comment by NotMrPolo-real** [comment]
> > but in the mods folder idk how to do that, any help?
> 
> https://codename-engine.com/wiki/modding/scripting/custom-classes

thanks you!
